import Link from "next/link";
import type { UsPanel, Stance } from "@/lib/us-panel";
import { MASTERS } from "@/lib/masters";
import MasterRadar from "./MasterRadar";
import { T } from "@/lib/i18n";

// 股神英文名 + 流派(UI 框架层双语;MASTERS.name/school 是中文规范名)。判词/理由正文仍为 AI 中文(V1)。
const MASTER_EN: Record<string, string> = {
  buffett: "Buffett",
  duan: "Duan Yongping",
  serenity: "Serenity",
  druckenmiller: "Druckenmiller",
  sentiment: "Sentiment",
};
const SCHOOL_EN: Record<string, string> = {
  buffett: "Value · Moat",
  duan: "Value · Business Model",
  serenity: "Alpha · Supply-chain Bottleneck",
  druckenmiller: "Alpha · Macro Liquidity",
  sentiment: "Flow · Money Flow",
};

function scoreColor(s: number): string {
  if (s >= 70) return "text-up";
  if (s >= 55) return "text-accent";
  if (s >= 40) return "text-muted";
  return "text-down";
}
function scoreBar(s: number): string {
  if (s >= 70) return "bg-up";
  if (s >= 55) return "bg-accent";
  if (s >= 40) return "bg-muted";
  return "bg-down";
}

// 注:st.verdict / st.judgment / st.reasoning 是每票 AI 判词正文 —— 保持中文(V1),只双语化卡片框架。
function StanceCard({ nameZh, nameEn, schoolZh, schoolEn, st }: { nameZh: string; nameEn: string; schoolZh: string; schoolEn: string; st: Stance }) {
  return (
    <div className="rounded-xl border border-line bg-surface p-4">
      <div className="mb-2 flex items-baseline justify-between gap-2">
        <div>
          <span className="text-sm font-semibold text-ink"><T zh={nameZh} en={nameEn} /></span>
          <span className="ml-2 text-[10px] text-faint"><T zh={schoolZh} en={schoolEn} /></span>
        </div>
        <span className={`font-mono text-lg font-semibold tabular-nums ${scoreColor(st.score)}`}>{st.score}</span>
      </div>
      <span className="inline-flex rounded border border-line bg-surface-2 px-2 py-0.5 text-[11px] font-medium text-ink">
        {st.verdict}
      </span>
      <div className="mt-1.5 h-0.5 w-full overflow-hidden rounded-full bg-surface-2">
        <div className={`h-full ${scoreBar(st.score)}`} style={{ width: `${Math.max(2, Math.min(100, st.score))}%` }} />
      </div>
      <p className="mt-2 text-sm font-medium leading-snug text-ink">{st.judgment}</p>
      <p className="mt-1 text-xs leading-relaxed text-muted">{st.reasoning}</p>
    </div>
  );
}

function EmptyCard({ nameZh, nameEn, schoolZh, schoolEn }: { nameZh: string; nameEn: string; schoolZh: string; schoolEn: string }) {
  return (
    <div className="rounded-xl border border-dashed border-line-2 bg-base/30 p-4">
      <div className="mb-2 flex items-baseline justify-between gap-2">
        <div>
          <span className="text-sm font-semibold text-muted"><T zh={nameZh} en={nameEn} /></span>
          <span className="ml-2 text-[10px] text-faint"><T zh={schoolZh} en={schoolEn} /></span>
        </div>
        <span className="text-xs text-faint"><T zh="未覆盖" en="Not covered" /></span>
      </div>
      <p className="text-xs text-faint"><T zh={`这只票还没跑过${nameZh}的判读。`} en={`No ${nameEn} read has been run on this stock yet.`} /></p>
    </div>
  );
}

function ChainChips({ syms }: { syms?: string[] }) {
  if (!syms || syms.length === 0) return <span className="text-faint">—</span>;
  return (
    <span className="inline-flex flex-wrap gap-1.5">
      {syms.map((s) => (
        <Link
          key={s}
          href={`/stock/${s}?market=us`}
          className="rounded border border-line bg-surface-2 px-1.5 py-0.5 font-mono text-[11px] text-muted transition hover:border-accent/40 hover:text-accent"
        >
          {s}
        </Link>
      ))}
    </span>
  );
}

export default function MasterPanel({ data }: { data: UsPanel }) {
  const covered = MASTERS.filter((m) => data.panel[m.key]).length;
  return (
    <section className="mb-8">
      <header className="mb-3 flex items-baseline gap-3">
        <h2 className="text-lg font-semibold text-ink"><T zh={`${covered} 方独立评分`} en={`${covered} Independent Reads`} /></h2>
        <span className="text-xs text-faint"><T zh="五位投资人各按自身框架独立评分,分歧越大越值得关注" en="Five investors score independently by their own framework — the wider the spread, the more worth a look" /></span>
      </header>

      {/* 法务标注:人设是 AI 按公开方法论的模拟,非本人真实观点/持仓(放量前必须显著) */}
      <p className="mb-3 rounded-lg border border-line bg-surface-2/60 px-3 py-2 text-[11px] leading-relaxed text-muted">
        <span className="font-semibold text-faint"><T zh="AI 方法论模拟" en="AI methodology simulation" /></span> —{" "}
        <T
          zh="以下五方判读由 AI 依据各投资人公开的投资方法论生成,"
          en="The five reads below are generated by AI from each investor's publicly known methodology, "
        />
        <span className="font-medium text-ink"><T zh="并非本人真实观点、发言或持仓" en="and are not their actual views, statements, or holdings" /></span>
        <T zh=",亦不代表其本人。仅供研究参考,非投资建议。" en=", nor do they represent the individuals themselves. For research reference only — not investment advice." />
      </p>

      {/* 雷达图 hero:5 方评分即 5 维,形状本身就是分歧 */}
      <div className="mb-4 flex flex-col items-center gap-2 rounded-2xl border border-line bg-base/40 p-3 sm:flex-row sm:gap-5 sm:p-4">
        <div className="shrink-0">
          <MasterRadar panel={data.panel} />
        </div>
        <div className="flex-1 self-stretch sm:border-l sm:border-line sm:pl-5">
          {data.divergence ? (
            <>
              {/* 标题双语;分歧焦点正文 data.divergence 是 AI 生成,保持中文(V1) */}
              <div className="text-xs font-semibold text-accent"><T zh="分歧焦点" en="Where they disagree" /></div>
              <p className="mt-1.5 text-sm leading-relaxed text-ink">{data.divergence}</p>
            </>
          ) : (
            <p className="text-sm leading-relaxed text-muted">
              <T
                zh="雷达各顶点为一方评分,越靠外评分越高;形状越规整代表五方越一致,越不规则代表分歧越大。"
                en="Each vertex is one investor's score — farther out means higher. A regular shape means the five align; a jagged one means they disagree."
              />
            </p>
          )}
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {MASTERS.map((m) => {
          const st = data.panel[m.key];
          const nameEn = MASTER_EN[m.key] ?? m.name;
          const schoolEn = SCHOOL_EN[m.key] ?? m.school;
          return st ? (
            <StanceCard key={m.key} nameZh={m.name} nameEn={nameEn} schoolZh={m.school} schoolEn={schoolEn} st={st} />
          ) : (
            <EmptyCard key={m.key} nameZh={m.name} nameEn={nameEn} schoolZh={m.school} schoolEn={schoolEn} />
          );
        })}

        {/* 产业链定位 */}
        <div className="rounded-xl border border-line bg-base/40 p-4">
          <div className="text-[10px] font-mono uppercase tracking-wider text-faint"><T zh="产业链定位" en="Supply-chain position" /></div>
          <p className="mt-1 text-sm font-medium text-ink">
            {data.chain.industry}
            <span className="ml-2 rounded bg-surface-2 px-1.5 py-0.5 text-[10px] text-muted">{data.chain.layer}</span>
          </p>
          {/* 用干净的公司介绍 desc(AI 生成,保持中文 V1) */}
          {data.desc && <p className="mt-1 text-xs leading-relaxed text-muted">{data.desc}</p>}
          <div className="mt-2.5 space-y-1.5 text-xs">
            <div className="flex gap-2">
              <span className="shrink-0 text-faint"><T zh="上游" en="Upstream" /></span>
              <ChainChips syms={data.chain.upstream} />
            </div>
            <div className="flex gap-2">
              <span className="shrink-0 text-faint"><T zh="下游" en="Downstream" /></span>
              <ChainChips syms={data.chain.downstream} />
            </div>
          </div>
        </div>
      </div>

    </section>
  );
}
