"""把 Claude 在对话中给的 BG 报告序列化到 data/analyses/ 缓存。

这样 watchlist 里的股票点开 /stock/[code] 就直接显示对话报告，
不需要再让用户点"生成 BG 深度分析"按钮。

这是 Claude 对话 → 文件系统 的桥接器。
未来每次 Claude 在对话里给完报告，就调用本脚本导入。

Usage:
    uv run python -m scripts.seed_conversation_reports
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
ANALYSES_DIR = ROOT / "data" / "analyses"
ANALYSES_DIR.mkdir(exist_ok=True)


def make_dim(name: str, score: float, grade: str, summary: str,
             details: list[str], flags: list[str]) -> dict:
    return {
        "name": name,
        "score": score,
        "grade": grade,
        "details": [f"💬 {summary}"] + [f"• {d}" for d in details] if summary else [f"• {d}" for d in details],
        "flags": flags,
    }


# ---- 报告数据（来自 Claude 对话）----

REPORTS = [
    # ============ 紫金矿业 A 股 ============
    {
        "code": "601899",
        "market": "a",
        "name": "紫金矿业",
        "industry": "有色金属-黄金",
        "overall_score": 83.25,
        "overall_grade": "🏆 重点候选",
        "verdict": "段永平和巴菲特会重点关注。陈景河式工程师 CEO + 全球资源 + 民营机制 = 教科书级价投。当前估值不便宜但前瞻 PE 10.6 倍 + ROE 21% + FCF/净利 1.46 = 好公司在合理价格。建议现价小仓持有，跌到 ¥30 以下分批加。",
        "raw_quote": {
            "code": "601899", "name": "紫金矿业", "price": 37.19,
            "change_pct": -0.69, "market_cap": 9.87e11,
            "pe_ttm": 19.38, "pb": 5.84,
            "industry": "有色金属-黄金"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 82, "通过（LLM）",
                "铜+金+锂三轮驱动，矿产品毛利率 61.56% 业内顶级",
                ["铜：电气化 + AI 算力 + 数据中心，长期需求向上",
                 "金：避险 + 央行连续 14 个月增持",
                 "锂：从底部反转，2026 产能 +380%",
                 "资源极长，矿石资源量 +36% 至 8550 万吨"],
                ["🟢 多金属对冲了单一商品风险", "🟢 长坡厚雪，10 年视角清晰"]),
            "moat": make_dim("护城河", 88, "通过（LLM）",
                "全球矿权 + 成本曲线领先 + 民营机制 + 持续并购整合能力",
                ["护城河类型：资源 / 成本优势 / 规模 / 并购能力",
                 "卡莫阿铜矿、Las Bambas、Manono 锂矿全球布局",
                 "矿产品毛利率 61.56% = 业内最低成本之一",
                 "2026.3 拟 182 亿控股赤峰黄金"],
                ["🟢 巴菲特 100 亿打击测试扛得住"]),
            "management": make_dim("管理层", 88, "通过（LLM）",
                "陈景河（创始人 CEO + 工程师）60+ 岁仍在一线，段永平最爱类型",
                ["历史决策 90%+ 正确：刚果、海外扩张、提前布局锂",
                 "资本配置：海外并购 + 同时降低负债率（-3.63 pct）",
                 "稳定分红 + 回购历史良好"],
                ["🟢 民营机制 + 国际化经验在 A 股稀缺",
                 "🟡 高杠杆扩张需持续监控（长期借款+应付债券 1123 亿）"]),
            "financials": make_dim("财务质量", 85, "通过",
                "ROE 21% + FCF/净利 1.46 + 矿产品毛利 61.56% = 顶级",
                ["营收 +15.0%（2025）, 归母净利 +61.5%",
                 "经营 CF 754 亿 > 净利 517 亿（FCF 转化优秀）",
                 "资产负债率 51.56%（-3.63 pct）持续优化"],
                ["✅ ROE > 15%", "✅ FCF / 净利 > 1", "✅ 资负 < 70%"]),
            "valuation": make_dim("估值", 75, "通过",
                "前瞻 PE 10.6x + 18 家分析师全 buy + 目标价 +24%",
                ["PE TTM 19.38（表面不便宜）",
                 "PE 2026E = 10.6（明显进入便宜区间）",
                 "国际可比：BHP 7、Rio Tinto 6，紫金溢价合理",
                 "段永平十年回本法：~10.6 年达到门槛"],
                ["🟢 18 位分析师全部买入评级"]),
            "circle": make_dim("能力圈", 78, "在能力圈",
                "在 Leslie 能源/材料/资源圈，国民级公司，研报多",
                ["故事简单：民营矿业龙头 + 全球资源 + 多金属对冲",
                 "5 分钟讲清楚",
                 "60% 海外资产需关注非洲/南美政治"],
                ["🟢 在 Leslie 能力圈内：能源/材料/资源"]),
        },
        "sell_triggers": [
            "陈景河退休且接班人非工程师+长期主义类型",
            "海外重大资产被国有化",
            "资产负债率反弹至 65%+",
            "ROE 跌破 15% 持续 2 年",
            "综合毛利率连续 2 季下滑 > 5pct",
        ],
        "sector": "能源/材料/资源",
        "concepts": ["黄金", "铜", "锂矿", "民营矿业", "全球化", "出海", "新能源金属"],
    },

    # ============ 紫金矿业 H 股 ============
    {
        "code": "02899",
        "market": "hk",
        "name": "紫金矿业H",
        "industry": "有色金属-黄金",
        "overall_score": 83.25,
        "overall_grade": "🏆 重点候选",
        "verdict": "同 A 股，H 股折价 15-20%，长期估值更便宜。如果你港股账户活跃可选 H 股。",
        "raw_quote": {
            "code": "02899", "name": "紫金矿业H", "price": 30.5,
            "change_pct": -0.5, "market_cap": 8.0e11,
            "pe_ttm": 16.4, "pb": 4.9, "industry": "有色金属-黄金"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 82, "通过（LLM）", "同 A 股", ["见 A 股"], []),
            "moat": make_dim("护城河", 88, "通过（LLM）", "同 A 股", ["见 A 股"], []),
            "management": make_dim("管理层", 88, "通过（LLM）", "同 A 股", ["见 A 股"], []),
            "financials": make_dim("财务质量", 85, "通过", "同 A 股", ["见 A 股"], []),
            "valuation": make_dim("估值", 78, "通过", "H 股折价更便宜", ["PE 比 A 股低 15-20%"], ["🟢 H 股折价"]),
            "circle": make_dim("能力圈", 78, "在能力圈", "同 A 股", ["见 A 股"], []),
        },
        "sell_triggers": ["同 A 股", "加 + 港币汇率风险"],
        "sector": "能源/材料/资源",
        "concepts": ["黄金", "铜", "锂矿", "民营矿业", "全球化", "出海", "新能源金属", "AH 折价"],
    },

    # ============ 天坛生物 ============
    {
        "code": "600161",
        "market": "a",
        "name": "天坛生物",
        "industry": "医药生物-生物制品",
        "overall_score": 75.3,
        "overall_grade": "🏆 重点候选",
        "verdict": "段永平视角：血浆站牌照是真护城河（2001 年起国家基本停批），跟茅台'赤水河+茅台镇'不可复制同逻辑。当前 Q1 利润 -48% 看着吓人但是行业价格周期，基本面没坏。这种时候买好公司，最像段永平 2018 加仓腾讯（监管压力+短期业绩压力+商业模式没变）。建议现价小仓试水，跌到 ¥12 加仓。",
        "raw_quote": {
            "code": "600161", "name": "天坛生物", "price": 16.05,
            "change_pct": 0.06, "market_cap": 2.85e10,
            "pe_ttm": 35.0, "pb": 3.5,
            "industry": "医药生物-生物制品"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 75, "通过（LLM）",
                "血液制品是医药里最稳的细分之一，老龄化+重症医疗+自给率提升",
                ["中国血制品自给率仅 60%，进口替代空间大",
                 "ROIC 长期稳定（不同于强周期股）",
                 "短期价格压力 + 增值税新政（2026.1.1 起 13%）"],
                ["🟢 长坡：老龄化主题"]),
            "moat": make_dim("护城河", 85, "通过（LLM）",
                "血浆站牌照（2001 年起冻结审批）+ 行业 CR4 80% + 国药集团整合",
                ["在营 85 家血浆站，分布 16 省，采浆量 20% 市占率",
                 "国药拟 46.99 亿收购派林（21.03%）",
                 "整合后市占率有望 30%+，行业第一",
                 "巴菲特 100 亿打击测试：完全扛得住"],
                ["🟢 牌照护城河是 BG 框架最硬的一种",
                 "🟢 类比茅台白酒许可证"]),
            "management": make_dim("管理层", 72, "警告（LLM）",
                "国药旗下，国企但战略清晰（收购派林、扩产）",
                ["收购派林是清晰的整合思路",
                 "极低负债（9.69%）+ 持续扩产",
                 "国企决策效率 / 灵魂型 CEO 缺失"],
                ["🟡 国企天花板就这样，比一般国企好"]),
            "financials": make_dim("财务质量", 75, "通过",
                "资产负债率 9.69% 极健康 + 毛利率 43.81% + 现金充裕",
                ["营收 +9.62%，归母净利 -22%（行业价格回调）",
                 "2026Q1 净利 -48%（短期压力）",
                 "ROE ~12-13%（略低于 15% 标准但稳定）"],
                ["🟢 资负 9.69% 极健康", "🟡 利润短期承压"]),
            "valuation": make_dim("估值", 70, "通过",
                "PE 2026E = 23x，PB 3.5x，机构增持评级",
                ["PE 静态 35x，但 2026/2027/2028 = 29.6/23.1/18.8",
                 "估值随业绩释放快速回落",
                 "兴业证券增持评级"],
                ["🟢 当前估值反映短期压力，没反映派林整合"]),
            "circle": make_dim("能力圈", 70, "在能力圈",
                "在医药生物圈内，大白马研报多",
                ["故事简单：国企+牌照+老龄化+进口替代",
                 "血液制品 know-how 需要时间学习"],
                ["🟢 在 Leslie 能力圈内：医药生物"]),
        },
        "sell_triggers": [
            "血液制品被纳入大规模集采",
            "ROE 跌破 8% 持续 2 年",
            "派林并购失败 / 终止",
            "母公司中国生物战略转向",
            "血浆站监管事件",
        ],
        "sector": "医药生物",
        "concepts": ["血液制品", "血浆站牌照", "老龄化", "国药集团", "进口替代", "资产注入"],
    },

    # ============ 美光科技 MU ============
    {
        "code": "MU",
        "market": "us",
        "name": "美光科技",
        "industry": "半导体-存储芯片",
        "overall_score": 79.75,
        "overall_grade": "边缘重点候选（等回调）",
        "verdict": "段永平视角：MU 的'HBM 三寡头+AI 算力卡位+FCF 爆发'逻辑能完全看懂（类似买苹果的 thesis），但段永平铁律：周期股要在底部买。当前是周期上行中段（接近顶部），大概率赞同但不参与。等回调到 $400-450 才是 BG 入场点。",
        "raw_quote": {
            "code": "MU", "name": "美光科技", "price": 546.0,
            "change_pct": 0.8, "market_cap": 6.1e11,
            "pe_ttm": 16.0, "pb": 6.5,
            "industry": "半导体-存储芯片"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 75, "通过（LLM）",
                "AI 算力关键上游，HBM = GPU 的命根子，2026 产能全售罄",
                ["HBM TAM 2025 $35B → 2028 $100B+ = 3x 增长",
                 "客户：NVIDIA / AMD / Broadcom / Google / Meta / AWS",
                 "HBM4 已为 NVIDIA Vera Rubin 量产；Feynman GPU 定制 HBM",
                 "但 DRAM/NAND 依然是强周期股（3-4 年周期）"],
                ["🟢 AI 算力刚需 + 寡头垄断", "🟡 周期股属性不变"]),
            "moat": make_dim("护城河", 82, "通过（LLM）",
                "HBM 三寡头（海力士 50% + 三星 35% + 美光 15%）",
                ["资本壁垒：建一座 HBM 厂 $10B+",
                 "技术壁垒：stacked DRAM + TSV + Logic Die",
                 "1α DRAM + EUV 节点领先",
                 "NVIDIA Feynman 定制 HBM 客户长期绑定"],
                ["🟢 准入门槛极高", "🟡 美光老三，份额 5%→15%→25%"]),
            "management": make_dim("管理层", 75, "通过（LLM）",
                "CEO Sanjay Mehrotra（SanDisk 创始人 + 业内技术老兵）",
                ["历史决策：减产保价（2022-2023）、HBM3e、HBM4 量产 NVIDIA",
                 "建厂+回购+分红平衡",
                 "不是创始人级控制但工程师派"],
                ["🟢 接近段永平喜欢的工程师 CEO 类型"]),
            "financials": make_dim("财务质量", 88, "通过",
                "GAAP 毛利率 74.4% + 净利 +773% + EPS $12.07 单季",
                ["营收 Q2 $23.86B (+70% YoY)",
                 "ROE 估算 100%+ 年化（周期顶部）",
                 "云存储业务 +160% YoY",
                 "但 FY2023 是亏损的（周期波动）"],
                ["🟢🟢 GAAP 毛利率超过 NVIDIA", "🟡 周期顶部数据"]),
            "valuation": make_dim("估值", 80, "通过",
                "Forward PE 8.6-12.5x，比 NVIDIA 便宜 2.5x",
                ["FY2026 共识：营收 $76B, EPS $34",
                 "分析师目标价 $249-$1000 区间",
                 "段永平十年回本法：8.6-12.5 年达标",
                 "但 YTD +70%、12 个月 +302%，已涨多"],
                ["🟢 估值便宜在 AI 主题股里罕见",
                 "🔴 入场时机不佳（接近周期顶部）"]),
            "circle": make_dim("能力圈", 75, "在能力圈（你 crypto+AI 圈内）",
                "AI 上下游 + GPU/HBM 算力链路",
                ["21 年进圈 + 项目方背景，对 AI 算力敏感",
                 "美股 + 周期半导体 know-how 复杂",
                 "跌 50% 测试：周期股暴跌 60-70% 常态"],
                ["🟢 你的 AI 圈内能力圈适配"]),
        },
        "sell_triggers": [
            "NVIDIA/AMD/hyperscaler 削减 AI Capex",
            "HBM ASP 连续 2 季环比 -15%",
            "三星 HBM4 大规模突破份额超越",
            "GAAP 毛利率跌破 50%（周期反转）",
            "NVIDIA Feynman 定制 HBM 合同失败",
        ],
        "sector": "AI 上下游",
        "concepts": ["HBM", "AI 算力", "存储芯片", "美国本土制造", "NVIDIA 供应链", "半导体周期"],
    },

    # ============ 华锡有色 ============
    {
        "code": "600301",
        "market": "a",
        "name": "华锡有色",
        "industry": "有色金属-锡",
        "overall_score": 65.8,
        "overall_grade": "学习池边缘",
        "verdict": "段永平视角：资源+牌照是真东西，但'锡价 1Q26 同比 +48%、铟价 +62%'是周期上行中段，不是击球区。等下次锡价大跌 30%，公司基本面没坏，那时候是真便宜。⚠️ 警惕'朋友说有矿要并进来'这类消息驱动 — 这正是 Stop Doing List 第一条。",
        "raw_quote": {
            "code": "600301", "name": "华锡有色", "price": 54.05,
            "change_pct": -1.2, "market_cap": 3.42e10,
            "pe_ttm": 42.56, "pb": 5.5,
            "industry": "有色金属-锡"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 62, "通过（LLM）",
                "周期股但锡/锑/铟有结构性需求（光伏+半导体+AI）",
                ["3 大矿山可采年限 20-26 年",
                 "矿石资源量 +36% 至 8550 万吨",
                 "周期性强 + 资本密集 = 差生意特征"],
                ["🟡 锡锑铟是战略稀缺金属"]),
            "moat": make_dim("护城河", 76, "通过（LLM）",
                "广西国资矿权 + 矿权整合政策 + 资源金属垄断",
                ["3 大矿山：铜坑、高峰锡矿、佛子冲",
                 "广西矿权整合（15 个矿业权）受益",
                 "锡锑铟战略稀缺金属"],
                ["🟢 牌照+资源护城河双重"]),
            "management": make_dim("管理层", 66, "警告（LLM）",
                "广西国资，稳健但天花板",
                ["资本结构持续优化（负债率 -6.5 pct）",
                 "1Q26 末资负 30.85%",
                 "国企：决策效率 vs 灵魂型 CEO 缺失"],
                ["🟡 国企背景，比私营矿企质量低一档"]),
            "financials": make_dim("财务质量", 70, "通过",
                "营收 +25.31%, 归母净利 +21.75%, 资负 30.85%",
                ["1Q26 营收 11.57 亿 (-7% YoY)",
                 "1Q26 净利 1.82 亿 (+18.54% YoY)",
                 "ROE ~13% (周期股调整后达标)"],
                ["🟢 财务结构健康", "🟡 单季波动剧烈"]),
            "valuation": make_dim("估值", 52, "警告",
                "PE 42.56（静态）/ 25-28（2026 预期），不便宜",
                ["机构目标价 ¥47.4（基于 2026 PE 20x）",
                 "现价 ¥54 比目标价高 14%",
                 "周期上行中段，估值已反映预期"],
                ["🔴 周期上行中段，估值压力大"]),
            "circle": make_dim("能力圈", 65, "在能力圈",
                "在 Leslie 能源/材料圈内但周期股最难做",
                ["懂金属周期+库存周期+地缘（缅甸佤邦）",
                 "跌 50% 测试需要真懂周期"],
                ["🟡 周期股需要更深的能力圈认知"]),
        },
        "sell_triggers": [
            "锡价 LME 跌破 $26000 持续 6 个月",
            "缅甸佤邦锡矿恢复 100% 产能",
            "公司单季净利环比连续 2 季下滑 > 20%",
            "实控人/国资委层面治理结构剧变",
            "矿业事故/安全停产",
        ],
        "sector": "能源/材料/资源",
        "concepts": ["锡", "锑", "铟", "国资矿业整合", "广西矿权", "战略稀有金属"],
    },

    # ============ 天赐材料 ============
    {
        "code": "002709",
        "market": "a",
        "name": "天赐材料",
        "industry": "新能源-电解液",
        "overall_score": 62.1,
        "overall_grade": "学习池偏下",
        "verdict": "段永平视角：重资产+强周期+技术替代风险，三个特征都是我躲的。当前正在景气上升中段（六氟磷酸锂年涨 280%），这种暴涨之后大概率暴跌。机构按 '2026 +400%' 给的预测，只要锂价回调一点就破灭。不碰。",
        "raw_quote": {
            "code": "002709", "name": "天赐材料", "price": 43.48,
            "change_pct": 1.2, "market_cap": 8.86e10,
            "pe_ttm": 65.1, "pb": 4.91,
            "industry": "新能源-电解液"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 58, "警告（LLM）",
                "强周期 + 重资产 + 技术替代风险（固态电池）",
                ["全球电解液市占 36.4%（龙头）",
                 "六氟磷酸锂 +280% 单年价格波动",
                 "在建产能 100 万吨（重资产）",
                 "固态电池硫化物路线长期颠覆风险"],
                ["🔴 三个差生意特征同时存在"]),
            "moat": make_dim("护城河", 68, "通过（LLM）",
                "规模+垂直整合+长协客户",
                ["全球电解液市占 36.4%",
                 "长协 294.5 万吨锁定到 2030",
                 "六氟磷酸锂自产自给",
                 "二线追赶激烈（多氟多、新宙邦）"],
                ["🟡 商品化产品技术差异化弱"]),
            "management": make_dim("管理层", 65, "警告（LLM）",
                "徐金富创始人+化工背景，但 2022-2024 扩产节奏不佳",
                ["历史决策正确：早期切入电解液、自产六氟、固态前瞻",
                 "国际化布局摩洛哥（不算激进）"],
                ["🟡 中性偏正面国内民营"]),
            "financials": make_dim("财务质量", 62, "警告",
                "ROE 7.55% 远低于 15% 标准 + 周期股波动剧烈",
                ["营收 +33%, 归母净利 +181%",
                 "Q4 单季毛利率 30.12%（强反弹）",
                 "ROE 2024 = 3.63%, 2025 = 7.55% 波动大"],
                ["🔴 ROE 远低于 BG 标准", "🟡 周期反弹"]),
            "valuation": make_dim("估值", 55, "警告",
                "PE TTM 65（贵） vs PE 2026 = 11（依赖完美兑现）",
                ["PE 反差 65 → 12 = 6 倍 = 完美预期",
                 "PEG 0.37 看似漂亮但周期股不适用",
                 "段永平十年回本：65 年（按 2025） / 12.5 年（按 2026）"],
                ["🔴 赌的是完美兑现", "🔴 下行风险更大"]),
            "circle": make_dim("能力圈", 65, "在能力圈",
                "锂电产业链在 AI 圈内但最难做的细分",
                ["价格周期+库存周期+技术替代叠加",
                 "用过产品+跟踪 3 年+测试大概率未达"],
                ["🟡 锂电材料是最难的细分"]),
        },
        "sell_triggers": [
            "六氟磷酸锂价格回落至 ¥10 万以下持续 3 个月",
            "ROE 2026 实际兑现低于 15%",
            "全球电解液市占率跌破 30%",
            "宁德/比亚迪自研电解液产能上线",
            "固态电池量产装车",
        ],
        "sector": "AI 上下游/能源",
        "concepts": ["锂电材料", "电解液", "六氟磷酸锂", "固态电池", "新能源车", "宁德供应链"],
    },

    # ============ 航天彩虹 ============
    {
        "code": "002389",
        "market": "a",
        "name": "航天彩虹",
        "industry": "国防军工-无人机",
        "overall_score": 58.75,
        "overall_grade": "⛔ 过滤（双重一票否决）",
        "verdict": "段永平视角：PE 90 倍意味着假设未来 10 年净利每年涨 30%，即使彩虹-7 全卖完这种假设也不敢做。2025H1 营收 -20%、净利转亏，军工就是这样反复。我连 PE 25-30 的茅台苹果都嫌贵，会买 PE 90 倍的军工？永远不会。⛔ 估值+财务双重一票否决。",
        "raw_quote": {
            "code": "002389", "name": "航天彩虹", "price": 28.0,
            "change_pct": 2.5, "market_cap": 2.8e10,
            "pe_ttm": 90.0, "pb": 4.0,
            "industry": "国防军工-无人机"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 65, "警告（LLM）",
                "军工+低空经济双线，但订单波动剧烈",
                ["沙特 40 亿订单 + 阿联酋 5.4 亿洽谈",
                 "YH-1000S 货运无人机商业化",
                 "2025 H1 转亏 vs 2026 Q1 +427% — swing 严重"],
                ["🟡 故事好但业绩反复"]),
            "moat": make_dim("护城河", 80, "通过（LLM）",
                "航天科技集团+国家队身份+无人机产业链链长",
                ["军用无人机出口占中国 70%",
                 "全产业链布局（碳纤维+动力+整机）",
                 "彩虹-7 全球少数高空+隐身+长航时三合一",
                 "国家定位'无人机产业链链长'"],
                ["🟢 国家队身份不可复制"]),
            "management": make_dim("管理层", 65, "警告（LLM）",
                "国企，业绩平滑/成本控制能力不足",
                ["三费占比 +35.86% YoY（成本失控）",
                 "国企天花板 + 灵魂型 CEO 缺失"],
                ["🔴 三费失控信号"]),
            "financials": make_dim("财务质量", 50, "一票否决",
                "2025H1 转亏 + 业绩剧烈波动 + 综合毛利率 13.84% 暴跌 23pct",
                ["归母净利 -49 万（2025H1 转亏）",
                 "综合毛利率 13.84%（-23.16 pct）",
                 "三费占比 +35.86%",
                 "ROE 接近 0"],
                ["🔴🔴 三连击：转亏 + 毛利暴跌 + 三费失控"]),
            "valuation": make_dim("估值", 30, "一票否决",
                "PE 85-91 倍极贵 + 段永平十年回本期 85+ 年",
                ["机构 2026 PE = 85-91 倍",
                 "段永平十年回本：85+ 年（远超 15 年门槛）",
                 "市场已 priced in 完美增长 + 全部订单"],
                ["🔴🔴🔴 BG 框架最严的一票否决"]),
            "circle": make_dim("能力圈", 55, "圈外",
                "军工不在 Leslie 明确能力圈，业务黑箱",
                ["军工业务是黑箱（订单/政府/技术不公开）",
                 "需要懂军贸+军方采购周期"],
                ["🔴 不在能力圈"]),
        },
        "sell_triggers": [
            "2026 半年报净利不及预期（< 1.5 亿）",
            "沙特/阿联酋订单延期或取消",
            "PE 突破 120 倍",
            "三费占比继续上升",
            "军方采购预算下调",
        ],
        "sector": "AI 上下游/国防",
        "concepts": ["无人机", "低空经济", "军贸出口", "国家队", "彩虹系列", "AI agent"],
    },

    # ============ Circle Internet ============
    {
        "code": "CRCL",
        "market": "us",
        "name": "Circle Internet",
        "industry": "金融科技-稳定币",
        "overall_score": 64.15,
        "overall_grade": "学习池",
        "verdict": "段永平视角：'生意逻辑我懂，但你不能控制你的主要收入来源（美联储利率），这就不是好生意'。USDC 合规品牌+网络效应+Agent payments 99.8% 卡位都不错，但收入 95% 依赖国债利息 + Coinbase 分成 + PS 10x = 估值已 priced in 完美。能力圈外（如果你是 crypto 老兵则达标）。",
        "raw_quote": {
            "code": "CRCL", "name": "Circle Internet", "price": 113.12,
            "change_pct": 1.8, "market_cap": 2.5e10,
            "pe_ttm": 100.0, "pb": 5.5,
            "industry": "金融科技-稳定币"
        },
        "dimensions": {
            "business_model": make_dim("商业模式", 68, "警告（LLM）",
                "稳定币基础设施+Agent payments 99.8%+Visa/Intuit 嵌入",
                ["USDC 流通 $77B (+28% YoY)",
                 "链上交易量 $21.5T (+263% YoY)",
                 "收入 95% 依赖美国短债利息 = 利率敏感性致命",
                 "与 Coinbase 收入分成（议价权弱）"],
                ["🟢 链上活跃度反超 USDT", "🔴 命运不在自己手里"]),
            "moat": make_dim("护城河", 75, "通过（LLM）",
                "合规品牌+监管护城河+Agent payments 卡位",
                ["USDC = 合规稳定币首选（vs USDT 灰色历史）",
                 "Visa/Intuit/Apollo/BlackRock 真实嵌入",
                 "x402 协议 99.8% AI agent payments 份额",
                 "GENIUS Act/CLARITY Act 主要推动者"],
                ["🟡 USDT 网络效应仍更大", "🔴 JPM Coin/CBDC 威胁"]),
            "management": make_dim("管理层", 72, "通过（LLM）",
                "Jeremy Allaire（2013 创始）+ 持续监管对话",
                ["早期走合规路线（vs Tether 灰色）",
                 "推动 GENIUS/CLARITY Act",
                 "收入多元化战略（Arc, Agent Wallets）"],
                ["🟢 连续创业者 + 长期主义"]),
            "financials": make_dim("财务质量", 60, "警告",
                "营收+20% 但净利-15% + 毛利率 27%→22% 下滑",
                ["Q1 营收 $694M (+20% YoY)",
                 "调整后 EBITDA $151M (+24%, 53% margin)",
                 "净利 $55M (-15% YoY)",
                 "毛利率 22%（去年 27%）"],
                ["🔴 增长不赚钱信号", "🟡 自由现金流健康"]),
            "valuation": make_dim("估值", 55, "警告",
                "PS 2026E ~10x，PE TTM 100x，已 priced in 完美预期",
                ["分析师目标价 $145.8 (+29% 上行)",
                 "MS 5/19 升目标 $80→$106（仍低于现价）",
                 "段永平十年回本：~40 年"],
                ["🔴 估值依赖完美兑现"]),
            "circle": make_dim("能力圈", 45, "圈外（默认 Leslie）",
                "美股+crypto+稳定币，理解门槛极高",
                ["美股不在 v0 能力圈",
                 "加密+利率+监管+链上数据多维理解",
                 "对 crypto 圈内人可调高到 75-80"],
                ["🔴 默认能力圈外", "🟡 你 21 年进圈+项目方背景可调高"]),
        },
        "sell_triggers": [
            "美联储一次降息 75bp+",
            "Q2 2026 毛利率继续下滑 < 20%",
            "USDC 链上交易量增速跌破 50%",
            "JP Morgan Coin/Fed CBDC 推出",
            "CLARITY 法案被推翻",
        ],
        "sector": "互联网/金融科技",
        "concepts": ["稳定币", "USDC", "AI agent payments", "Web3", "监管套利", "国债套利", "Coinbase 关联"],
    },
]


def write_report(report: dict) -> Path:
    """把对话报告写成 analyses cache JSON。"""
    code = report["code"]
    market = report["market"]
    payload = {
        "code": code,
        "name": report["name"],
        "market": market,
        "industry": report["industry"],
        "overall_score": report["overall_score"],
        "overall_grade": report["overall_grade"],
        "verdict": report["verdict"],
        "llm_used": True,
        "llm_model": "claude-conversation",
        "dimensions": report["dimensions"],
        "raw_quote": report["raw_quote"],
        "sell_triggers": report["sell_triggers"],
        "financials_history": {},  # 后续可补充
        "financials": {},
        "updated_at": datetime.now().isoformat(timespec="seconds"),
        "elapsed_seconds": 0,
        # 新字段
        "sector": report.get("sector", ""),
        "concepts": report.get("concepts", []),
    }
    path = ANALYSES_DIR / f"{code}_{market}.json"
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def main():
    print(f"开始导入 {len(REPORTS)} 份对话报告到 analyses cache …\n")
    for report in REPORTS:
        path = write_report(report)
        print(f"  ✅ {report['name']:<14} ({report['code']:<6}/{report['market'].upper():<3}) "
              f"得分 {report['overall_score']:>5.1f} → {path.name}")
    print(f"\n完成。共 {len(REPORTS)} 份报告写入 {ANALYSES_DIR}")
    print("打开 http://localhost:3001/stock/601899?market=a 验证")


if __name__ == "__main__":
    main()
